The Object class has been renamed to StatementObject
php-xapi/symfony-serializer pull request #9
Opened 2018-04-15 18:05 UTC by djoudi

2018-04-15 18:49 UTC, djoudi commented
@xabbuh

2018-04-15 20:28 UTC, xabbuh commented
In `composer.json` we need to replace `"php-xapi/model": "^1.0 || ^2.0"` with `"php-xapi/model": "^1.0 || ^2.0 || 3.0"`.

2018-04-15 20:30 UTC, xabbuh requested changes

2018-04-15 20:30 UTC, xabbuh commented on src/Normalizer/ObjectNormalizer.php
> +        return $data instanceof StatementObject;
For backwards compatibility, this should be `return $data instanceof Object || $data instanceof StatementObject;`.

2018-04-15 20:30 UTC, xabbuh commented on src/Normalizer/ObjectNormalizer.php
> +        return 'Xabbuh\XApi\Model\Activity' === $type || 'Xabbuh\XApi\Model\StatementObject' === $type || 'Xabbuh\XApi\Model\StatementReference' === $type || 'Xabbuh\XApi\Model\SubStatement' === $typ
here we need to check for the old class name too

2018-04-15 20:30 UTC, xabbuh commented on src/Normalizer/ObjectNormalizer.php
> +        $object = $this->denormalizeData($data['object'], 'Xabbuh\XApi\Model\StatementObject', $format, $context);
same here

2018-04-15 20:30 UTC, xabbuh commented on .travis.yml
> +      env: xdebug="yes"
using Xdebug for the code coverage on one job is enough, I would just remove it for the new entries and keep it for the PHP 7.0 job

2018-04-16 15:38 UTC, xabbuh requested changes

2018-04-16 15:38 UTC, xabbuh commented on src/Normalizer/ObjectNormalizer.php
> +        $object = (class_exists('Xabbuh\XApi\Model\Object'))?$this->denormalizeData($data['object'], 'Xabbuh\XApi\Model\Object', $format, $context):$this->denormalizeData($data['object'], 'Xabbuh\XAp
I would write it this way:

```php
if (class_exists('Xabbuh\XApi\Model\StatementObject')) {
    $object = $this->denormalizeData($data['object'], 'Xabbuh\XApi\Model\StatementObject', $format, $context);
} else {
    $object = $this->denormalizeData($data['object'], 'Xabbuh\XApi\Model\Object', $format, $context);
}
```

2018-04-16 15:38 UTC, xabbuh commented on src/Normalizer/StatementNormalizer.php
> +        $object = $this->denormalizeData($data['object'], 'Xabbuh\XApi\Model\StatementObject', $format, $context);
same here

2018-04-24 08:05 UTC, closed without merging